services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celpip-web
    restart: always
    ports:
      - "31421:3000"
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
